AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

Layout/LineLength:
  Max: 120
  Exclude:
    - lib/esi/client/*.rb
    - spec/lib/esi/client/*_spec.rb
    - spec/lib/esi/client_spec.rb
    - Rakefile

Metrics/BlockLength:
  Exclude:
    - Rakefile
    - spec/**/*_spec.rb

Metrics/ModuleLength:
  Exclude:
    - lib/esi/client/*.rb

Metrics/ParameterLists:
  Exclude:
    - lib/esi/client/*.rb

Naming/FileName:
  Exclude:
    - lib/esi-sdk.rb
    - spec/lib/esi-sdk_spec.rb
